name: CI WhatToDoApp Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Client steps
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for client
        run: |
          cd client
          npm install

      - name: Lint code for client
        run: |
          cd client
          npm run lint

      - name: Check styling for client
        run: |
          cd client
          npm run prettier:check

      - name: Audit dependencies for client
        run: |
          cd client
          npm audit --audit-level=moderate

      - name: Type check client
        run: |
          cd client
          npm run type-check

      - name: Run tests for client
        run: |
          cd client
          npm test

      # Server steps
      - name: Set up Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Lint code for server
        run: |
          cd server
          npm run lint

      - name: Check styling for server
        run: |
          cd server
          npm run prettier:check

      - name: Audit dependencies for server
        run: |
          cd server
          npm audit --audit-level=moderate

      - name: Type check server
        run: |
          cd server
          npm run type-check

      - name: Run tests for server
        run: |
          cd server
          npm test
